-- ==========================================
-- Phase 7: 著作権ガード & BGMライブラリ
-- ==========================================

-- 1. 著作権フリーBGMライブラリ
CREATE TABLE IF NOT EXISTS bgm_library (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  url TEXT NOT NULL, -- 音源ファイルへのリンク
  category TEXT, -- 'Action', 'Relax', 'Epic' など
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. 著作権チェック結果を保存するテーブル
CREATE TABLE IF NOT EXISTS copyright_checks (
  clip_id BIGINT REFERENCES clips(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending', -- 'clear', 'detected', 'fair_use'
  detected_details JSONB, -- 検知された曲名やアーティスト名
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  PRIMARY KEY (clip_id)
);

-- 3. clips テーブルに権利情報を追加
ALTER TABLE clips ADD COLUMN IF NOT EXISTS copyright_status TEXT DEFAULT 'unchecked';
ALTER TABLE clips ADD COLUMN IF NOT EXISTS used_bgm_id BIGINT REFERENCES bgm_library(id);

-- 4. 権利違反時に自動で非公開にするトリガー
CREATE OR REPLACE FUNCTION enforce_copyright()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.copyright_status = 'violation' THEN
    NEW.status := 'banned'; -- 権利違反なら即座にBAN(非表示)
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_copyright_enforcement
BEFORE UPDATE ON clips
FOR EACH ROW
WHEN (OLD.copyright_status IS DISTINCT FROM NEW.copyright_status)
EXECUTE FUNCTION enforce_copyright();
