-- ==========================================
-- Phase 4: プライベートメッセージング (DM) の導入
-- ==========================================

-- 1. メッセージテーブルの作成
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  receiver_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. セキュリティ設定 (RLS)
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 自分が送信した、または自分宛のメッセージのみ閲覧可能
CREATE POLICY "Users can view their own messages" 
ON messages FOR SELECT 
USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

-- メッセージの送信
CREATE POLICY "Users can send messages" 
ON messages FOR INSERT 
WITH CHECK (auth.uid() = sender_id);

-- 3. インデックス追加 (検索高速化)
CREATE INDEX IF NOT EXISTS idx_messages_participants ON messages(sender_id, receiver_id);
