-- ==========================================
-- Phase 6: スケーラビリティ & セキュリティガード
-- ==========================================

-- 1. アクション回数を記録するテーブル
CREATE TABLE IF NOT EXISTS user_action_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL, -- 'post', 'comment', 'like'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. レート制限をチェックする関数
-- 1時間以内に指定回数以上の操作があればエラーを投げます
CREATE OR REPLACE FUNCTION check_rate_limit() 
RETURNS TRIGGER AS $$
DECLARE
  action_count INT;
  limit_count INT := 10; -- 1時間の制限回数 (例: 10回)
BEGIN
  -- 1時間以内の同一アクション回数をカウント
  SELECT COUNT(*) INTO action_count 
  FROM user_action_logs 
  WHERE user_id = auth.uid() 
  AND action_type = TG_ARGV[0]
  AND created_at > now() - interval '1 hour';

  IF action_count >= limit_count THEN
    RAISE EXCEPTION 'Rate limit exceeded. Please try again later.';
  END IF;

  -- ログを記録
  INSERT INTO user_action_logs (user_id, action_type) VALUES (auth.uid(), TG_ARGV[0]);
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. クリップ投稿とコメントに制限を適用
DROP TRIGGER IF EXISTS trg_limit_posts ON clips;
CREATE TRIGGER trg_limit_posts
BEFORE INSERT ON clips
FOR EACH ROW EXECUTE FUNCTION check_rate_limit('post');

DROP TRIGGER IF EXISTS trg_limit_comments ON comments;
CREATE TRIGGER trg_limit_comments
BEFORE INSERT ON comments
FOR EACH ROW EXECUTE FUNCTION check_rate_limit('comment');

-- 4. BANされたユーザーの動画を自動で非表示にするポリシー
ALTER TABLE clips ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Hide banned clips" ON clips;
CREATE POLICY "Hide banned clips" ON clips
FOR SELECT
USING (status != 'banned');
